title: "GitHub Main Releases"
description: "A daily-updated stable releases dashboard"
theme: jekyll-theme-cayman
# If you want to enable optional plugins, you can:
# plugins:
#   - jekyll-seo-tag
