name: generate-JSON-of-releases

on:
  schedule:
    # Run every day at 12:00 UTC (adjust if needed)
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script to generate JSON
        run: python main.py

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/data/releases.json
          git commit -m "Update stable releases JSON [skip ci]" || echo "No changes to commit"
          git push
